language: java
jdk:
- oraclejdk8
sudo: required

branches:
only: develop

before_script:
  - wget http://services.gradle.org/distributions/gradle-4.5.1-bin.zip
  - unzip gradle-4.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH

addons:
  sonarcloud:
    organization: carledriss-github
    token:
      secure: tEFCJw3xwtgBzS9vSLiuqxOlMBYVnh+/GnjTe5IFSLD2AFHplNUOynclP3QN0n72q+I+AWqbyRwDQ+PDD5fiuyjp/fOmHgInkFapNf0hwDhSlX0DCe1Qg0+lzplGoQyASry4zJ4Nx3uLCGolE4aAawaAj+Dvbla1okulr3SsT+ot29P7X1K1S1Gy6DEG///127Z+brArzT44ntNTV75rEqZyn0qeDBlrAEc56/nDzBoNZ2hrvS67UA+raicYDOg/KYirLb10ozO79flNQbvjzEgzHFgzdtXyAQqA3S5kT7TLMJfdfbzln5R6tBOsDfvCKi6tf1jG8Fe0z5RiAB7h/XzGpVglKYUfURP1pdP1MDhT3F2pRv2W38PnfkQ2Jpq4fVnoaLVsKz33OJsmakRRbk+FFVBEPG7Rksco9pYLgICwzVnX5Y0tZzp5BzuErhVpBqqn6B1PLo5lHe4EnEhs9a8ImU/UeDYkMyqovL6QHiljfhkmSi3ir63IP7+Rx1oiYUQp2Iwmpzq4LgS7gZ2pvp/9DL5F7EUun+uhRspVrYf8uyhjFsNndNRG6E8IjxyiokS+gqBN1xI8G7GA7oNfhbwBJUnzsVLzcXMZ/KT7HvZUUsutyaHdX8rPYGDAr8jcRHh7+AAkkwOcJAcfDlI6MdXLgYbof+A2FtwOB9O9+yE=
    github_token:
      secure: JEF8KAxca1AkUr9P7CyHsZyFrZtbJy9jiV2DRLDytHDT4ZQLfsq2EWbig0iucFx9FiOoL/skfjkRy14bv9FIVt+5yjPA1Ww8Va7NgaGGuFWqRP/1sxASDEx3RoccvP+JcKMUYlPsWBe0IFUgDCYuiDt0TtptDYpV/wHNR/z9USRYtb1BRRDCb8WJ87DJMaFSoskIzr2awBd0e70LrQubrzZvN9dovsIPVZ4pztnacdycbm99/xNjh2SXNkWqkQsJE+711l2J3+9tPGbnUGyq2D20nyDmWlvgvsQFzB5y4H6YdD48KQ0/hDzlFSmyfr3kb3C1kYRYvnTo/Ao7x5QCkhsWr2vqsmTSfA6fiV/2PQn9vLAqNi2jRbckIDIPT8kkTx0cPg5hoSryx0ofU7Q2oEYEKeDI6tk5ufv7EXPCranX7WFC4N5sQZ3lUExuRgZvinscqiSZzwQmcNJ+5D8xCiBHHsyFxXovC4jWIhsZQbgn4Kq3MKERa8I+CK0vnOebKXHMHQEyQU8RdvNo26szyXkWFxYm2RFizt+leQMOVPSH8JLXMNHfE7nwxSKQLfu4MQ0hXU94o7QANH2bBDkGWAKspML9k90h+bRzH8zElKEAZucgy08FJtLRwK/2eeLmm+GXyGybPfYw8JQzpPG8dWhUdWUW78QVIwAybzjtE7A=
    branches:
    - develop
script:
- gradle check
- sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
